---

- block:
  - name: "Update all Packages (Mode: {{ maintenance.upgrade_type }} on (Debian/Ubuntu))"
    apt:
      upgrade={{ maintenance.upgrade_type }}
      update_cache=yes
      force=yes
      install_recommends=yes
    register: check_install
    changed_when: "'No packages will be installed' not in check_install.stdout"
    #changed_when: "'No packages will be installed, upgraded, or removed.' not in check_install.stdout"
    notify:
    - "Restart Server"
    - "Wait for Server to come back"

  - name: "Autoremove unused Packages (Debian/Ubuntu)"
    apt: autoremove=yes
    ignore_errors: yes

  - name: "Check if anything needs autoremoving (Debian/Ubuntu)"
    shell: apt-get autoremove -y --dry-run
    become: True
    register: check_autoremove
    changed_when: "' 0 to remove' not in check_autoremove.stdout"
    failed_when: "check_autoremove.rc != 0"
    check_mode: no

  - name: "Autoremove unused Packages (Debian/Ubuntu) "
    command: apt-get autoremove -y
    when: "check_autoremove.rc == 0 and ' 0 to remove' not in check_autoremove.stdout"
    register: autoremove

  when: ansible_os_family == "Debian"
  environment:
    LC_ALL: C
    LANG: en

