---

- name: "Run Debian Update Process"
  import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: "Run SLES Update Process"
  import_tasks: sles.yml
  when: ansible_os_family == "Suse"

- name: "Run CentOS / RedHat Update Process"
  import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: "Run Virtualenv Update Process"
  import_tasks: virtualenv.yml


# Check for Reboot
- stat: path=/var/run/reboot-required
  register: reboot_required
  check_mode: no

- name: "Inform that Server needs restart and is disallowed"
  debug:
    msg="Server {{ inventory_hostname }} needs restart, please perform / start this manually."
  when: reboot_required.stat.exists and not maintenance.allow_reboot
  changed_when: reboot_required.stat.exists and not maintenance.allow_reboot

- name: "Inform that Server needs restart and will be restarted"
  debug:
    msg="Server {{ inventory_hostname }} needs restart and will be restarted, now."
  when: reboot_required.stat.exists and maintenance.allow_reboot
  changed_when: reboot_required.stat.exists and maintenance.allow_reboot
  notify:
  - "Restart Server"

...
