---

- name: "Run Debian Update Process"
  include: debian.yml
  when: ansible_os_family == "Debian"

- name: "Run SLES Update Process"
  include: sles.yml
  when: ansible_os_family == "Suse"

# Check for Reboot

- stat: path=/var/run/reboot-required
  register: reboot_required
  always_run: True

- name: "Inform that Server needs restart and is disallowed"
  debug:
    msg="Server {{ inventory_hostname }} needs restart, please perform / start this manually."
  when: reboot_required.stat.exists and not maintenance.allow_reboot
  changed_when: reboot_required.stat.exists and not maintenance.allow_reboot

- name: "Inform that Server needs restart and will be restarted"
  debug:
    msg="Server {{ inventory_hostname }} needs restart and will be restarted, now."
  when: reboot_required.stat.exists and maintenance.allow_reboot
  changed_when: reboot_required.stat.exists and maintenance.allow_reboot
  notify:
  - "Restart Server"
  - "Wait for Server to come back"

...
