---

- name: "Ensure NGINX PPA is avaliable"
  apt_repository:
    repo="{{ nginx.ppa }}"
    state=present
  when: 'ansible_distribution == "Ubuntu" and nginx.use_ppa == "yes"'
  tags:
    - setup

- name: "Ensure NGINX Repository Key is avalibale"
  apt_key: 
    url="http://nginx.org/keys/nginx_signing.key"
    state=present

- name: "Ensure NGINX Repository is avaliable"
  apt_repository:
    repo="deb http://nginx.org/packages/ubuntu/ {{ ansible_distribution_release }} nginx"
    state=present
    filename="nginx.list"
  when: 'ansible_distribution == "Ubuntu" and nginx.use_repo == "yes"'
  tags:
    - setup

- name: "Install NGINX packages"
  apt:
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
    - nginx
    - python-selinux
  when: ansible_os_family == "Debian"
  tags:
    - setup

- name: "Ensure directories for site specific configurations are present"
  file:
    path=/etc/nginx/{{ item }}
    state=directory
    owner=root
    group=root
    mode="u=rwx,g=rx,o=rx"
  with_items:
    - "sites-available"
    - "sites-enabled"
  tags:
    - setup

- name: "Copy NGINX configuration file"
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
  tags:
    - setup
    - configuration
  notify:
   - "Restart NGINX"

- name: "Copy NGINX default configuration file"
  template:
    src=default.conf.j2
    dest=/etc/nginx/conf.d/default.conf
  tags:
    - setup
    - configuration

- name: "Copy NGINX default site configuration file"
  template:
    src=default.j2
    dest=/etc/nginx/sites-available/default
  tags:
    - setup
    - configuration

- name: "Start NGINX Service"
  service:
    name=nginx
    state=started
    enabled=yes
  tags:
    - setup
    - configuration
