---

- name: "Install NGINX PPA"
  apt_repository:
    repo="{{ nginx.ppa }}"
    state=present
    #filename="nginx"
  when: 'ansible_distribution == "Ubuntu" and nginx.use_ppa == "yes"'
  tags:
    - setup

- name: "Install the NGINX packages"
  apt:
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
    - nginx
    - python-selinux
  #environment: env
  when: ansible_os_family == "Debian"
  tags:
    - setup

- name: "Ensure the directories for site specific configurations are present"
  file:
    path=/etc/nginx/{{ item }}
    state=directory
    owner=root
    group=root
    mode="u=rwx,g=rx,o=rx"
  with_items:
    - "sites-available"
    - "sites-enabled"
  tags:
    - setup

- name: "Copy the NGINX configuration file"
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
  tags:
    - setup
    - configuration
  notify:
   - "Restart NGINX"

- name: "Copy the NGINX default configuration file"
  template:
    src=default.conf.j2
    dest=/etc/nginx/conf.d/default.conf
  tags:
    - setup
    - configuration

- name: "Copy the NGINX default site configuration file"
  template:
    src=default.j2
    dest=/etc/nginx/sites-available/default
  tags:
    - setup
    - configuration

- name: "Start the NGINX Service"
  service:
    name=nginx
    state=started
    enabled=yes
  tags:
    - setup
    - configuration
