---

- include: base.yml

#- name: Create the configurations for sites
#  template:
#    src=site.j2
#    dest=/etc/nginx/sites-avaliable/{{ item['server']['file_name'] }}.conf
#  with_items: nginx_sites
#  when: nginx_sites|lower != 'none'
#  tags:
#    - configuration
#  notify:
#   - reload nginx

#- name: Create the link for site enabled specific configurations
#  file:
#    src=/etc/nginx/sites-available/{{ item['server']['file_name'] }}.conf
#    path=/etc/nginx/sites-enabled/{{ item['server']['file_name'] }}.conf
#    state=link
#  with_items: nginx_sites
#  when: nginx_sites|lower != 'none'
#  tags:
#    - configuration
#  notify:
#   - reload nginx
