---

- name: "Install the haproxy packages"
  apt: name={{ item }} state=present update_cache=no
  with_items:
    - haproxy
    - hatop
  when: ansible_os_family == "Debian"
  ignore_errors: True

- name: "Ensure the directories (/etc/haproxy/haproxy.cfg.d)is present"
  file:
    path=/etc/haproxy/haproxy.conf.d
    state=directory
    owner=root
    group=root
    mode="u=rwx,g=rx,o=rx"

- name: "Copy the /etc/default/haproxy file"
  template:
    src=default-haproxy.j2
    dest=/etc/default/haproxy
    force=yes
    owner=root
    group=root
    mode="u=rw,g=r,o=r"
  notify:
    - "Restart HAProxy"

- name: "Copy the base config for HAProxy"
  template:
    dest="/etc/haproxy/haproxy.conf.d/00-base.cfg"
    src="00-base.cfg.j2"
    force=yes
    owner=root
    group=root
    mode="u=rw,g=r,o=r"
  notify:
    - "Assemble HAProxy Config"

- name: "Ensure the HAProxy service is started and enable on boot"
  service:
    name=haproxy
    state=started
    enabled=yes
  ignore_errors: True
