- name: Restart Server
  command: shutdown -r now "Reboot triggered by Ansible after system updates"
  async: 0
  poll: 0
  ignore_errors: true
  when: reboot_required.stat.exists and ansible_os_family == "Debian"

- name: Wait for Server to come back
  local_action: 
    wait_for 
    host={{ inventory_hostname }}
    state=started
    delay=20
    timeout=300
  sudo: false
  when: reboot_required.stat.exists
