---

- name: "Restart Server"
  reboot:
    msg: "Reboot by Ansible-Playbook after Update"
    reboot_timeout: 3600
  register: result
  notify: "Info if Reboot was sucessful"
  when: reboot_required.stat.exists and maintenance.allow_reboot

- name: "Info if Reboot was sucessful"
  debug:
    msg: "{{ inventory_hostname }} has rebooted: {{ result.rebooted }}, it has taken: {{ result.elapsed }} seconds"
  when: reboot_required.stat.exists and maintenance.allow_reboot and result

- name: "Delete reboot_required file"
  file:
    path=/var/run/reboot-required
    state=absent

...
