---

dependencies:

  - base-preseed
  - { role: maintenance,
      maintenance: {
        upgrade_type: "full",
        allow_reboot: false
      }
    }
  - { role: psdash,
      psdash: {
        path: "/usr/local/venv-psdash",
        mode: "agent"
      }
    }

  - { role: psdash,
      psdash: {
        path: "/usr/local/venv-psdash",
        mode: "master"
      }
    }

  - { role: apache_httpd,
    }


...
