---

- hosts: all
  become: true
  gather_facts: true

  roles:
    - base-preseed
    - { role: maintenance,
        maintenance: {
          upgrade_type: "full",
          allow_reboot: false
        }
      }

- hosts: all
  become: true
  gather_facts: true

  roles:
    - psdash
...
