---

- hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: "Ensure Python2 and Aptitude is installed"
      raw: apt-get -y install python aptitude

- hosts: all
  become: true
  gather_facts: true

  roles:
    - base-preseed

...
