---

- hosts: all
  become: true
  gather_facts: true

  roles:
    - "lmu.ansible_role.base-preseed"

    #- { role: "lmu.ansible_role.maintenance",
    #    maintenance: {
    #      upgrade_type: "full",
    #      allow_reboot: false
    #    }
    #  }

...
