#!/usr/bin/env ansible-playbook
# vim:set nu:ft=ansible:

---

- hosts: cmdb
  become: true

  roles:
    - base-preseed
    - { role: maintenance,
        maintenance: {
          upgrade_type: "full",
          allow_reboot: false
        }
      }
    #- lmu.ansible_role.i_doit
    - lmu.ansible_role.firewalld
    - apache_httpd

  vars_files:
    - secrets.yml

  pre_tasks:

    #- meta: end_play

...
