---

- hosts: all
  become: true
  gather_facts: true
  serial: "{{ SERIAL_COUNT | default('100%') }}"

  tasks:

  - name: Restart Server
    command: sleep 2 && shutdown -r now "Forced Reboot triggered by Ansible"
    async: 1
    poll: 0
    ignore_errors: true

  - name: Wait for Server to come back
    local_action:
      wait_for
      host={{ ansible_ssh_host | default(inventory_hostname) }}
      port=22
      search_regex=OpenSSH
      state=started
      delay=20
      timeout=300
    become: false
