---

- hosts: all
  become: true
  gather_facts: true
  serial: "{{ SERIAL_COUNT | default('100%') }}"

  tasks:

  - name: Restart Server
    reboot:
      reboot_timeout: 3600
    register: result

  - name: "info if Reboot was sucessful"
    debug:
      msg: "{{ inventory_hostname }} has rebooted: {{ result.rebooted }}, it has taken: {{ result.elapsed }} seconds"
