---

- hosts: genetic
  become: true

  roles:
  - { role: maintenance,
      maintenance: {
        upgrade_type: "full",
        allow_reboot: false
      }
    }
  - plone-base
  - supervisor

  tasks:
    - name: "Install rsync, used to copy the data to the new server"
      apt:
        name: rsync
        state: present
        update_cache: true
        cache_valid_time: 3600
      tags:
        - rsync

    - name: "Install virtualenv and related packages"
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
        cache_valid_time: 3600
      loop:
        - virtualenv
        - libpython2.7-dev
      tags:
        - virtualenv

    - name: "Ensure dedicated buildout-data-directory is owned by user plone_daemon"
      file:
        path: "/srv/genetic/"
        state: directory
        owner: plone_daemon
        group: plone_group
        mode: "u=rwx,g=rwx,o=rx"
        recurse: yes
      tags:
        - virtualenv

# I comment this role because it requires some buildout consolidation
# - hosts: genetic
#   become: true
#
#   handlers:
#     - include: roles/supervisor/handlers/main.yml
#
#   roles:
#   -  { role: zc.buildout,
#        buildout: {
#           program_path: /opt/,
#           data_path: /srv/,
#           directory: genetic,
#           src: {
#               type: git,
#               src: "https://github.com/starzel/buildout.git",
#               rev: master,
#           },
#           config: local_production.cfg,
#           python: python2.7,
#           buildout_user: plone_buildout,
#           requires_secrets: true,
#           secrets: 'templates/secrets.cfg.j2',
#           login: 'admin',
#           password: 'admin',
#           mode: '',
#         }}

- hosts: genetic
  become: true

  roles:
    #- varnish
    - apache_httpd

  handlers:
    - include: roles/apache_httpd/handlers/main.yml

  tasks:
    # Apache
    - name: "Ensure Apache2 default Enabled VHost is absent"
      file:
         state: absent
         path: /etc/apache2/sites-enabled/000-default.conf

    - name: "Ensure the log directories are present"
      file:
        path: /var/log/apache2/{{ item }}
        state: directory
        owner: root
        group: adm
        mode: "u=rwx,g=rx,o=rx"
      loop:
        - genetik
      tags:
        - apache

    - name: Enable HTTP and HTTPS Ports
      community.general.ufw:
        rule: allow
        name: "WWW Full"
        comment: HTTP and HTTPS
      tags:
        - apache

    # SSH Settings
    - name: Enable SSH Zugriff aus den LMU VPN-Netzen
      community.general.ufw:
        rule: allow
        from_ip: "{{ item }}"
        port: 22,122
        proto: tcp
        direction: in
        comment: SSH aus LMU VPN-Netze zulassen
      loop:
        - 10.153.154.0/24
        - 10.153.155.0/24
        - 10.153.38.0/24
        - 10.153.39.0/24
        - 10.163.152.0/22
        - 10.163.156.0/22
        - 10.163.160.0/22
        - 10.163.164.0/22
        - 141.84.12.0/24
        - 141.84.13.0/24
        - 141.84.14.0/24
        - 141.84.15.0/24
        - 141.84.16.0/24
        - 141.84.17.0/24
        - 141.84.18.0/24
        - 141.84.19.0/24
        - 141.84.22.0/24
        - 141.84.23.0/24
        - 141.84.28.0/24
        - 141.84.29.0/24
        - 141.84.30.0/24
        - 141.84.31.0/24
        - 141.84.32.0/24
        - 141.84.33.0/24
        - 141.84.34.0/24
        - 2001:4ca0:4fff:9:0:1::/96
        - 2001:4ca0:4fff:9:0:2::/96
        - 2001:4ca0:4fff::/48
      tags:
        - ssh

    - name: Enable SSH Zugriff aus dem LMU Verwaltungsnetz
      community.general.ufw:
        rule: allow
        from_ip: 141.84.44.220
        name: SSH
        comment: SSH aus LMU Verwaltungsnetz (Firewall-Endpoint) zulassen
      tags:
        - ssh

    - name: Enable SSH für Zugriff aus der LRZ Compute Cloud
      community.general.ufw:
        rule: allow
        from_ip: 10.195.6.210
        name: SSH
        comment: SSH von LRZ CC Ansible-Controller zulassen
      tags:
        - ssh
