---

- include: base-preseed.yml
- include: maintenance.yml







- hosts: searchs
  sudo: true


- hosts: webfrontends
  sudo: true

# Infrastruktur

- include: sentry.yml
- include: monitor-master.yml


