---

- hosts: all
  become: true
  gather_facts: true

  roles:
    - { role: maintenance,
        maintenance: {
          upgrade_type: "full",
          allow_reboot: false
        }
      }


- hosts: all
  become: true
  serial: 1

  tasks:

    - block:
        - stat: path=/var/run/reboot-required
          register: reboot_required
          always_run: True

        - name: Restart Server
          command: shutdown -r +1 "Reboot triggered by Ansible after system updates"
          async: 0
          poll: 0
          ignore_errors: true
          when: reboot_required.stat.exists

        - name: Wait for Server to come back
          local_action:
            wait_for
            host={{ ansible_ssh_host | default(inventory_hostname) }}
            port=22
            search_regex=OpenSSH
            state=started
            delay=20
            timeout=300
          when: reboot_required.stat.exists
          become: false
      when: allow_reboot == true
