#!/usr/bin/env ansible-playbook
# vim:set nu:ft=ansible:

---

- hosts: nodemasters
  become: true

  vars:
    maintenance:
      allow_reboot: false

  roles:
    - base-preseed
    - { role: psdash,
      psdash: {
        path: "/usr/local/venv-psdash",
        mode: "master"
      }
    }
    - { role: maintenance,
        maintenance: {
          upgrade_type: "full",
          allow_reboot: false
        }
      }
    - ansible-master
#    - theforeman
#    - jenkins
    - { role: dashing,
      }

...
