---

- hosts: nodemasters
  become: true
  gather_facts: false

  tasks:
    - name: "Ensure Python2 and Aptitude is installed"
      raw: apt-get -y install python aptitude

- hosts: nodemasters
  become: true

  vars:
    maintenance:
      allow_reboot: false
  #vars_files:

  roles:
    - base-preseed
    - { role: maintenance,
        maintenance: {
          upgrade_type: "full",
          allow_reboot: false
        }
      }
    - ansible-master
    - theforeman
#    - jenkins
    - { role: dashing,
      }
    - { role: psdash,
        psdash: {
          path: "/usr/local/venv-psdash",
          mode: "master"
        }
      }
    - { role: nginx,
        nginx: {
          use_ppa: "yes",
          ppa: "ppa:nginx/stable"
        }
      }


...
