#!/usr/bin/env ansible-playbook
# vim:set nu:ft=ansible:

---

- hosts: nodemasters
  become: true

  vars:
    maintenance:
      allow_reboot: false

  roles:
    - ansible-master
#    - theforeman
#    - jenkins
    - { role: dashing,
      }

...
