---

- hosts: nodemasters
  become: true

  vars:
    maintenance:
      allow_reboot: false
  #vars_files:

  roles:
    - base-preseed
    - { role: maintenance,
        maintenance.allow_reboot: false
      }
#    - ansible-master
#    - theforeman
#    - jenkins
    - { role: dashing,
      }
    - { role: psdash,
        psdash: {
          path: "/usr/local/venv-psdash",
          version: '0.6.2',
          mode: "master"
        }
      }
    - { role: nginx,
      }


...
