---

- hosts: plone
  become: true

  roles:
    - base-preseed
    - plone-base
    - supervisor
    - { role: maintenance,
        maintenance: {
          upgrade_type: "full",
          allow_reboot: false
        }
      }

- hosts: zope-dbs-production
  become: true

  handlers:
    - include: roles/supervisor/handlers/main.yml

  roles:
    -  { role: zc.buildout,
         buildout: {
            path: /usr/local/,
            directory: buildout.zeoserver-production,
            src: {
                type: git,
                src: "https://github.com/loechel/lmu-iuk.buildout.git",
                rev: buildout-cleanup,
            },
            config: zeoserver-production.cfg,
            python: python2.7,
            buildout_user: plone_buildout,
            requires_secrets: true,
            secrets: 'templates/secrets.cfg.j2',
            login: 'admin',
            password: 'admin',
            mode: '',
         }}


- hosts: zope-dbs-failover-production
  become: true

  handlers:
    - include: roles/supervisor/handlers/main.yml

  roles:
    - { role: zc.buildout,
        buildout: {
           path: /usr/local/,
           directory: buildout.zeoserver-failover-production,
           src: {
               type: git,
               src: "https://github.com/loechel/lmu-iuk.buildout.git",
               rev: buildout-cleanup,
           },
           config: zeoserver-failover-production.cfg,
           python: python2.7,
           buildout_user: plone_buildout,
           requires_secrets: true,
           secrets: 'templates/secrets.cfg.j2',
           login: 'admin',
           password: 'admin',
           mode: '',
        }}


- hosts: zope-clients-production
  become: true

  handlers:
    - include: roles/supervisor/handlers/main.yml

  roles:
    -  { role: zc.buildout,
         buildout: {
            path: /usr/local/,
            directory: buildout.zope-clients-production,
            src: {
                type: git,
                src: "https://github.com/loechel/lmu-iuk.buildout.git",
                rev: buildout-cleanup,
            },
            config: zope-clients-production.cfg,
            python: python2.7,
            buildout_user: plone_buildout,
            requires_secrets: true,
            secrets: 'templates/secrets.cfg.j2',
            login: 'admin',
            password: 'admin',
            mode: '',
         }}


- hosts: plone
  become: true

  tasks:

    - name: "Restart Supervisor"
      service:
        name=supervisor
        state=restarted
        sleep=20
