---

- hosts: redmine
  become: true

  handlers:

    - include: roles/nginx/handlers/main.yml
    - include: roles/supervisor/handlers/main.yml

  vars:
    memcached_memory_limit: "512"

  vars_files:
    - secrets.yml

  roles:
    - base-preseed
    - { role: maintenance,
        maintenance: {
          upgrade_type: "full",
          allow_reboot: false
        }
      }

    - { role: redmine,
        redmine: {
          app_base_path: "/opt/redmine",
          data_base_path: "/data/redmine",
          log_base_path: "/var/log/redmine",
          run_base_path: "/var/run/redmine",
          svn_version: "3.1",
          src_url: "http://www.redmine.org/releases/",
          src_file: "redmine-3.2.0.tar.gz",
          checksum: "b1050c3a0e6effd5a704ef5003d9df06",
          domain: "redminetest.verwaltung.uni-muenchen.de"

        },
        redmine_instance: {
          # ref_vi-3: {
          #   name: "ref_vi-3",
          #   alias: ["sos", "anwendungsbetreuung"],
          #   db_name: "ref_vi-3",
          #   db_dev_name: "ref_vi-3-dev",
          #   db_test_name: "ref_vi-3-test",
          #   db_user: "{{ redmine_db.user }}",
          #   db_passwd: "{{ redmine_db.passwd }}",
          #   db_host: "127.0.0.1",
          #   lang: "de",
          #   log_level: "debug",
          #   plugins: [],
          #   themes: [],
          #   puma_port: "3003",
          #   nginx_port: "8003",
          #   nginx_ssl_port: "8443",
          # },
          # ref_vi-4: {
          #   name: "ref_vi-4",
          #   alias: ["it-sicherheit", "verz"],
          #   db_name: "ref_vi-4",
          #   db_dev_name: "ref_vi-4-dev",
          #   db_test_name: "ref_vi-4-test",
          #   db_user: "{{ redmine_db.user }}",
          #   db_passwd: "{{ redmine_db.passwd }}",
          #   db_host: "127.0.0.1",
          #   lang: "de",
          #   log_level: "debug",
          #   plugins: [],
          #   themes: [],
          #   puma_port: "3004",
          #   nginx_port: "8004",
          #   nginx_ssl_port: "8444",
          # },
          ref_vi-5: {
            name: "ref_vi-5",
            alias: ["internetdienste", "fiona"],
            db_name: "ref_vi-5",
            db_dev_name: "ref_vi-5-dev",
            db_test_name: "ref_vi-5-test",
            db_user: "{{ redmine_db.user }}",
            db_passwd: "{{ redmine_db.passwd }}",
            db_host: "127.0.0.1",
            lang: "de",
            log_level: "debug",
            plugins: [
              "redmine_agile",
              "redmine_checklists",
              "redmine_contacts",
              "redmine_contacts_helpdesk",
              #"redmine_didyoumean",
              #"redmine_spent_time",
              #"redmine-plugin-recurring-tasks",
              #"redmine_favorite_projects",
              #"redmine_spent_time_column",
              #"redmine_issue_templates",
              "redmine_tweaks",
              #"redmine_autowatch",
              #"redmine_knowledgebase",
              #"redmine_wiki_extensions",
              #"redmine_lmu_modifications",
              #"redmine_wiki_lists",
              #"redmine_local_avatars",
              "sidebar_hide",
            ],
            themes: [
              #"redmine-theme-lmu",
              "redmine-theme-gitmike",
              "a1",
              "circle"
            ],
            puma_port: "3000",
            nginx_port: "80",
            nginx_ssl_port: "443",
          },
        },
        redmine_plugins_download: [
          {
            name: "redmine_agile",
            oname: "Redmine Agile plugin (Pro version)",
            url: "https://mneme.informatik.unibw-muenchen.de/redmine-plugins/redmine_agile-1_4_0-pro.zip",
          },
          {
            name: "redmine_checklists",
            oname: "Redmine Checklist plugin (Pro version)",
            url: "https://mneme.informatik.unibw-muenchen.de/redmine-plugins/redmine_checklists-3_1_3-pro.zip",
          },
          {
            name: "redmine_contacts",
            oname: "Redmine CRM plugin (Pro version)",
            url: "https://mneme.informatik.unibw-muenchen.de/redmine-plugins/redmine_contacts-4_0_4-pro.zip",
          },
          {
            name: "redmine_contacts_helpdesk",
            oname: "Redmine Helpdesk plugin (Pro version)",
            url: "https://mneme.informatik.unibw-muenchen.de/redmine-plugins/redmine_contacts_helpdesk-3_0_1.zip",
          },
          {
            name: "redmine_issue_templates",
            oname: "Redmine Issue Templates",
            url: "https://bitbucket.org/akiko_pusu/redmine_issue_templates/downloads/redmine_issue_templates-0.1.1.zip",
          },
          {
            name: "redmine_wiki_extensions",
            oname: "Redmine Wiki Extensions plugin",
            url: "https://bitbucket.org/haru_iida/redmine_wiki_extensions/downloads/redmine_wiki_extensions-0.7.0.zip",
          },
          {
            name: "redmine_local_avatars",
            oname: "Redmine Local Avatars plugin",
            url: "https://launchpad.net/redminelocalavatars/trunk/0.1.1/+download/redmine_local_avatars-0.1.1.tar.gz",
          },
        ],
        redmine_plugins_git: [
          {
            name: "redmine_autowatch",
            oname: "Redmine Auto Watch plugin",
            url: "https://github.com/ZIMK/Redmine-AutoWatch.git",
            version: "master"
          },
          {
            name: "redmine_didyoumean",
            oname: "Did You Mean?",
            url: "https://github.com/abahgat/redmine_didyoumean.git",
            version: "master"
          },
          {
            name: "redmine_favorite_projects",
            oname: "Redmine Favorite Projects plugin",
            url: "https://github.com/alexandermeindl/redmine_favorite_projects.git",
            version: "1.0.5"
          },
          {
            name: "redmine_knowledgebase",
            oname: "Knowledgebase",
            url: "https://github.com/alexbevi/redmine_knowledgebase.git",
            version: "v3.1.0"
          },
          {
            name: "redmine_lmu_modifications",
            oname: "Redmine LMU modifications plugin",
            url: "https://github.com/loechel/redmine_lmu_modifications.git",
            version: "master"
          },
          {
            name: "redmine_spent_time",
            oname: "Redmine Spent Time Column",
            url: "https://github.com/eyp/redmine_spent_time.git",
            version: "3.1.2"
          },
          {
            name: "redmine_spent_time_column",
            oname: "Redmine Spent Time Column",
            url: "https://github.com/alexandermeindl/redmine_spent_time_column.git",
            version: "master"
          },
          {
            name: "redmine_tweaks",
            oname: "Redmine Tweaks",
            url: "https://github.com/alexandermeindl/redmine_tweaks.git",
            version: "0.5.6"
          },
          {
            name: "redmine_wiki_lists",
            oname: "Redmine Wiki Lists plugin",
            url: "https://github.com/tkusukawa/redmine_wiki_lists.git",
            version: "0.0.6"
          },
          {
            name: "redmine-plugin-recurring-tasks",
            oname: "Redmine Wiki Lists plugin",
            url: "https://github.com/nutso/redmine-plugin-recurring-tasks.git",
            version: "v1.6.0"
          },
          {
            name: "sidebar_hide",
            oname: "Sidebare Hide plugin",
            url: "https://github.com/bdemirkir/sidebar_hide.git",
            version: "master"
          },
        ],
        redmine_themes_download: [
          {
            name: "a1_theme",
            url: "https://mneme.informatik.unibw-muenchen.de/redmine-themes/a1_theme-1_1_3.zip"
          },
          {
            name: "circle_theme",
            url: "https://mneme.informatik.unibw-muenchen.de/redmine-themes/circle_theme-1_0_2.zip"
          }
        ],
        redmine_themes_git: [
          {
            name: "redmine-theme-lmu",
            url: "https://github.com/loechel/redmine-theme-lmu.git",
            version: "master"
          },
          {
            name: "redmine-theme-gitmike",
            url: "https://github.com/makotokw/redmine-theme-gitmike.git",
            version: "v1.0.7"
          }
        ],
        nginx: {
          use_ppa: "yes",
          ppa: "ppa:nginx/stable"
        }
      }
