---

- hosts: redmine
  become: true

  handlers:

    - include: roles/nginx/handlers/main.yml
    - include: roles/supervisor/handlers/main.yml

  vars:

  vars_files:
    - secrets.yml

  roles:
    - base-preseed
    - { role: maintenance,
        maintenance: {
          upgrade_type: "full",
          allow_reboot: false
        }
      }

    - { role: redmine,
        redmine: {
          app_base_path: "/opt/redmine",
          data_base_path: "/data/redmine",
          log_base_path: "/var/log/redmine",
          run_base_path: "/var/run/redmine",
          svn_version: "3.1",
          src_url: "http://www.redmine.org/releases/",
          src_file: "redmine-3.2.0.tar.gz",
          checksum: "b1050c3a0e6effd5a704ef5003d9df06",
          domain: "redminetest.verwaltung.uni-muenchen.de"

        },
        redmine_instance: {
          ref_vi-3: {
            name: "ref_vi-3",
            alias: ["sos", "anwendungsbetreuung"],
            db_name: "ref_vi-3",
            db_dev_name: "ref_vi-3-dev",
            db_test_name: "ref_vi-3-test",
            db_user: "{{ redmine_db.user }}",
            db_passwd: "{{ redmine_db.passwd }}",
            db_host: "127.0.0.1",
            lang: "de",
            log_level: "debug",
          },
          ref_vi-4: {
            name: "ref_vi-4",
            alias: ["it-sicherheit", "verz"],
            db_name: "ref_vi-4",
            db_dev_name: "ref_vi-4-dev",
            db_test_name: "ref_vi-4-test",
            db_user: "{{ redmine_db.user }}",
            db_passwd: "{{ redmine_db.passwd }}",
            db_host: "127.0.0.1",
            lang: "de",
            log_level: "debug",
          },
          ref_vi-5: {
            name: "ref_vi-5",
            alias: ["internetdienste", "fiona"],
            db_name: "ref_vi-5",
            db_dev_name: "ref_vi-5-dev",
            db_test_name: "ref_vi-5-test",
            db_user: "{{ redmine_db.user }}",
            db_passwd: "{{ redmine_db.passwd }}",
            db_host: "127.0.0.1",
            lang: "de",
            log_level: "debug",
          },
        },
        redmine_plugins: [
          {
            name: "redmine_agile",
            url: "https://mneme.informatik.unibw-muenchen.de/redmine-plugins",
            version: "1.4.0-pro"
          },
          {
            name: "redmine_contacts",
            url: "https://mneme.informatik.unibw-muenchen.de/redmine-plugins",
            version: "4.0.4-pro"
          },
          {
            name: "redmine_contacts_helpdesk",
            url: "https://mneme.informatik.unibw-muenchen.de/redmine-plugins",
            version: "3.0.1"
          },
          {
            name: "redmine_checklists",
            url: "https://mneme.informatik.unibw-muenchen.de/redmine-plugins",
            version: "3.1.3-pro"
          }
        ],
        nginx: {
          use_ppa: "yes",
          ppa: "ppa:nginx/stable"
        }
      }
