#!/usr/bin/env ansible-playbook
# vim:set nu:ft=ansible:

---

- hosts: redmine-dbs
  become: true

  vars_files:
    - secrets.yml

  roles:
    - base-preseed
    - maintenance
    - psdash
#    - lmu.ansible_role.redmine-db-postgres

- hosts: redmine-workers
  become: true

  vars_files:
    - secrets.yml

  roles:
    - base-preseed
    - maintenance
    - psdash
#    - lmu.ansible_role.redmine-worker

- hosts: redmine-frontends
  become: true

  vars_files:
    - secrets.yml

  roles:
    - base-preseed
    - maintenance
    - psdash
#    - lmu.ansible_role.redmine-frontend-apache_httpd
    #- lmu.ansible_role.redmine-frontend-nginx

...
