---
# Repair setup of some Servers

- hosts: all
  become: true
  gather_facts: true

  tasks:

  - name: Delete apt Repository
    lineinfile: 
      path: /etc/apt/source.list 
      state: absent
      line: deb http://apt.verwaltung.uni-muenchen.de/ZUV-DEB/ ZUV-DEB main
      regexp: ZUV-DEB

  - name: Install ntpd
    apt:
      name: ntp
      state: present

  - name: Update Apt Cache
    apt:
      update_cache: yes
