---

- hosts: solrs
  become: true

  vars:
    java:
      version: 7
      type: OpenJDK
      jdk: false


  roles:
    - base-preseed
    - java
    - { role: maintenance,
        maintenance: {
          upgrade_type: "full",
          allow_reboot: true
        }
      }
    - supervisor

  tasks:

    - name: remove .installed.cfg
      file:
        path='/usr/local/solr.buildout/.installed.cfg'
        state=absent


    - name: remove part elems
      file:
        path={{ item }}
        state=absent
      with_items:
        - '/usr/local/solr.buildout/parts/solr-download-stable'
        - '/usr/local/solr.buildout/parts/solr-download-latest'


- hosts: solr-masters-production
  become: true


  handlers:
    - include: roles/supervisor/handlers/main.yml

  roles:
    - { role: zc.buildout,
        buildout: {
          path: '/usr/local/',
          directory: 'solr.buildout',
          config: 'develop.cfg', #'production-master.cfg',
          requires_secrets: true,
          secrets: 'templates/secrets.cfg.j2',
          login: 'admin',
          password: 'admin',
          src: {
            src: 'https://github.com/loechel/solr.buildout.git',
            type: 'git',
            rev: 'master'
          }
        }
      }
  tasks:

    - name: "check if 'solr-instance' is present"
      supervisorctl:
        name="solr-instance"
        state=present

    - name: "Restart Supervisor"
      service:
        name=supervisor
        state=restarted
        sleep=5

- hosts: solr-slaves-production
  become: true

  handlers:
    - include: roles/supervisor/handlers/main.yml

  roles:
    - { role: zc.buildout,
        buildout: {
          path: '/usr/local/',
          directory: 'solr.buildout',
          config: 'develop.cfg', #'production-slave.cfg',
          requires_secrets: true,
          secrets: 'templates/secrets.cfg.j2',
          login: 'admin',
          password: 'admin',
          src: {
            src: 'https://github.com/loechel/solr.buildout.git',
            type: 'git',
            rev: 'master'
          }
        }
      }
  tasks:

    - name: "check if 'solr-instance' is present"
      supervisorctl:
        name="solr-instance"
        state=present

    - name: "Restart Supervisor"
      service:
        name=supervisor
        state=restarted
        sleep=5

- hosts: solr-masters-staging
  become: true


  handlers:
    - include: roles/supervisor/handlers/main.yml

  roles:
    - { role: zc.buildout,
        buildout: {
          path: '/usr/local/',
          directory: 'solr.buildout',
          config: 'develop.cfg', #'staging-master.cfg',
          requires_secrets: true,
          secrets: 'templates/secrets.cfg.j2',
          login: 'admin',
          password: 'admin',
          src: {
            src: 'https://github.com/loechel/solr.buildout.git',
            type: 'git',
            rev: 'master'
          }
        }
      }
  tasks:

    - name: "check if 'solr-instance' is present"
      supervisorctl:
        name="solr-instance"
        state=present

    - name: "Restart Supervisor"
      service:
        name=supervisor
        state=restarted
        sleep=5

- hosts: solr-slaves-staging
  become: true

  handlers:
    - include: roles/supervisor/handlers/main.yml

  roles:
    - { role: zc.buildout,
        buildout: {
          path: '/usr/local/',
          directory: 'solr.buildout',
          config: 'develop.cfg', #'staging-slave.cfg',
          requires_secrets: true,
          secrets: 'templates/secrets.cfg.j2',
          login: 'admin',
          password: 'admin',
          src: {
            src: 'https://github.com/loechel/solr.buildout.git',
            type: 'git',
            rev: 'master'
          }
        }
      }
  tasks:

    - name: "check if 'solr-instance' is present"
      supervisorctl:
        name="solr-instance"
        state=present

    - name: "Restart Supervisor"
      service:
        name=supervisor
        state=restarted
        sleep=5