
- hosts: nodemasters
  become: true
  gather_facts: true


  tasks:
    - name: "Ensure Git Repository on Master is up to date"
      git:
        # repo: https://github.com/lmu/lmu.ansible.playbooks.git
        repo: git@github.com:lmu/lmu.ansible.playbooks.git
        dest: /opt/lmu.ansible.playbooks
        update: yes
        clone: no
        recursive: yes
        track_submodules: yes
      environment:
        http_proxy: "{{ lookup('env', 'http_proxy') }}"
        https_proxy: "{{ lookup('env', 'https_proxy') }}"
      ignore_errors: yes

    - name: "Ensure playbook directories has correct owner and group"
      file:
        path="/opt/lmu.ansible.playbooks"
        state=directory
        owner="fachadmin"
        group="ansible"
        mode="u=rwX,g=rwX,o=rX"
        recurse=yes

    - name: "Ensure inventory / cmdb directories has correct file modes"
      file:
        path="{{ item }}"
        state=directory
        owner="fachadmin"
        group="ansible"
        mode="u=rwx,g=rwx,o=rx"
      with_items:
        - "/opt/lmu.ansible.playbooks/inventory-avaliable"
        - "/opt/lmu.ansible.playbooks/inventory-enabled"
        - "/opt/lmu.ansible.playbooks/unchecked-out"
        - "/opt/lmu.ansible.playbooks/checked-out"
        - "/opt/lmu.ansible.playbooks/cmdb"
      ignore_errors: yes

    - name: "Ensure inventory / cmdb files has correct file modes"
      file:
        path="{{ item }}"
        state=file
        owner="fachadmin"
        group="ansible"
        mode="u=rw,g=rw,o=r"
      with_fileglob:
        - "/opt/lmu.ansible.playbooks/inventory-avaliable/*"
        - "/opt/lmu.ansible.playbooks/unchecked-out/*"
        - "/opt/lmu.ansible.playbooks/checked-out/*"
        - "/opt/lmu.ansible.playbooks/cmdb/*"
      ignore_errors: yes
