---

- hosts: webproxies
  sudo: true
  gather_facts: true

  roles:
    - base-preseed
    - { role: maintenance,
        maintenance: {
          upgrade_type: "full",
          allow_reboot: true
        }
      }
    - supervisor
    - haproxy
    #- varnish
    - apache_httpd
