---

- hosts: all
  remote_user: fachadmin
  sudo: true
  #ask-sudo-pass: true

  vars:
    fachadmin-password: "$6$rounds=656000$7FWeGie/WDRfvfES$f3HA6STefV6JNgA668TFhyl2FR549VJkV7QW31/GHTWVELYT6YwWvx.C.2uIBxSp7eQvycS/b23AK7dH.QPNR/"
  roles:
    - base-preseed
    - zuv-preseed
    - { role: maintenance,
        maintenance: {
          upgrade_type: "full",
          allow_reboot: true
        }
      }
