---

- hosts: all
  become: true
  #remote_user: admin

  vars:
    admin_password: "$6$rounds=656000$7FWeGie/WDRfvfES$f3HA6STefV6JNgA668TFhyl2FR549VJkV7QW31/GHTWVELYT6YwWvx.C.2uIBxSp7eQvycS/b23AK7dH.QPNR/"
    fachadmin_password: "$6$rounds=656000$7FWeGie/WDRfvfES$f3HA6STefV6JNgA668TFhyl2FR549VJkV7QW31/GHTWVELYT6YwWvx.C.2uIBxSp7eQvycS/b23AK7dH.QPNR/"

  roles:
    - { role: zuv-preseed,
        proxy: {
          no_proxy: [
            "www.scm.verwaltung.uni-muenchen.de",
            "pypi.verwaltung.uni-muenchen.de",
            "www.intranet.verwaltung.uni-muenchen.de",
            "www.serviceportal.verwaltung.uni-muenchen.de",
            "cms-live-pm1",
            "cms-live-pm1.verwaltung.uni-munechen.de",
            "cms-live-pm2",
            "cms-live-pm2.verwaltung.uni-munechen.de",
            "cms-live-pm3",
            "cms-live-pm3.verwaltung.uni-munechen.de",
            "cms-live-app2",
            "cms-live-app2.verwaltung.uni-munechen.de",
            "cms-live-app3",
            "cms-live-app3.verwaltung.uni-munechen.de",
            "cms-live-app4",
            "cms-live-app4.verwaltung.uni-munechen.de",
            "search3",
            "search3.verwaltung.uni-munechen.de",
            "search4",
            "search4.verwaltung.uni-munechen.de",
            "*.zuv.uni-munechen.de",
            "10.110.0.0/24",
            "10.153.0.0/24",
            "172.23.0.0/24"
          ]
        }
      }
    - base-preseed
