---

- name: "Copy SSL Private-Key"
  copy:
    src="files/server-ssl/key/{{ redmine.domain }}_key.pem"
    dest="/etc/ssl/private/{{ redmine.domain }}_key.pem"
    force=yes
    owner=root
    group=root
    mode="u=r,g=r,o="
  tags:
    - redmine_setup
    - redmine_upgrade

- name: "Copy SSL Public Key"
  copy:
    src="files/server-ssl/crt/{{ redmine.domain }}_crt.pem"
    dest="/etc/ssl/private/{{ redmine.domain }}_crt.pem"
    force=yes
    owner=root
    group=root
    mode="u=r,g=r,o="
  tags:
    - redmine_setup
    - redmine_upgrade

- name: "Get LMU-CACERT-Chain"
  get_url:
    url="https://pki.pca.dfn.de/uni-muenchen-ca/pub/cacert/chain.txt"
    dest="/etc/ssl/private/lmu-chain.pem"
    owner=root
    group=root
    mode="u=rw,g=r,o="
  tags:
    - redmine_setup
    - redmine_upgrade

- name: "Install vhost.confs for sites"
  template:
    src=templates/apache_httpd_multiinstance.conf.j2
    dest=/etc/apache2/sites-available/redmine-multiinstance.conf
    force=yes
    mode="u=rw,g=r,o=r"
    owner=root
    group=root
  notify:
    - "Reload Apache httpd"
  tags:
    - redmine_setup
    - redmine_upgrade

- name: "Activate vhost.confs (Create the link for site enabled specific configurations)"
  file:
    src=/etc/apache2/sites-available/redmine-multiinstance.conf
    path=/etc/apache2/sites-enabled/redmine-multiinstance.conf
    force=yes
    state=link
    owner=root
    group=root
  notify:
    - "Reload Apache httpd"
  tags:
    - redmine_setup
    - redmine_upgrade
