---

- name: "Ensure Ruby is installed"
  apt: pkg={{ item }} state=present update_cache=yes install_recommends=yes
  with_items:
    - ruby2.0
    - ruby2.0-dev
    - ruby-dev
    - build-essential
    - ruby-rmagick
    - libmagick-dev
    - imagemagick
    - libmagickwand-dev
    - libmagickcore-dev
    - git
    - subversion
    #- bundler
  when: ansible_os_family == "Debian"

- name: "Ensure Group redmine exists"
  group:
    name="redmine"
    state=present

- name: "Ensure User redmine exists"
  user:
    name="redmine"
    group="redmine"
    force=true
    uid=980
    state=present

- name: "Ensure Base directories exists"
  file:
    path="{{ item }}"
    state=directory
    owner=redmine
    group=redmine
    mode="u=rwx,g=rx,o=rx"
  with_items:
    - "{{ redmine.app_base_path }}"
    - "{{ redmine.data_base_path }}"
    - "{{ redmine.log_base_path }}"

- name: "Install bundler for Ruby 2.0"
  command: gem2.0 install bundler
