---

- include: base.yml

- name: "Ensure Redmine Instance directories exists"
  file:
    path="{{ item }}/{{ redmine.name }}"
    state=directory
    owner=redmine
    group=redmine
    mode="u=rwx,g=rx,o=rx"
  with_items:
    - "{{ redmine.app_base_path }}"
    - "{{ redmine.data_base_path }}"
    - "{{ redmine.log_base_path }}"

- name: "Download Redmine to master"
  get_url:
    url: "{{ redmine.src_url}}/{{ redmine.src_file }}"
    dest: "./downloads/"
    mode: "u=rwx,g=rwx,o=rx"
    checksum: "md5:{{ redmine.checksum }}"
  delegate_to: 127.0.0.1
  become: false


- name: "Download Redmine"
  unarchive:
    src="{{ redmine.src_url}}/{{ redmine.src_file }}"
    dest="{{ redmine.app_base_path }}/{{ redmine.name }}"
    copy=no
    owner=redmine
    group=redmine
    mode="u=rwx,g=rx,o=rx"

#- name: "Move Redmine Download to directory"
#  copy:
#    src="{{ redmine.app_base_path}}/{{ redmine.name }}"
#    dest="{{ redmine.app_base_path}}/{{ redmine.name }}"
#    owner=redmine
#    group=redmine
#    force=yes
#    directory_mode=yes
#    copy=no
#    mode="u=rwx,g=r,o=r"


- name: "Copy Dependency File"
  copy:
    src="Gemfile.local"
    dest="{{ redmine.app_base_path}}/{{ redmine.name }}/redmine-3.2.0/Gemfile.local"
    force=yes
    owner=redmine
    group=redmine
    mode="u=rwx,g=r,o=r"

- name: "Copy Config Files"
  template:
    src={{ item }}.j2
    dest="{{ redmine.app_base_path}}/{{ redmine.name }}/redmine-3.2.0/config/{{ item }}"
    force=yes
    owner=redmine
    group=redmine
    mode="u=rwx,g=rx,o=rx"
  with_items:
    - database.yml
    - additional_environment.rb
    - configuration.yml
    - settings.yml

- name: "Ensure Redmine can write gems directory"
  file:
    path="{{ redmine.app_base_path}}/{{ redmine.name }}/redmine-3.2.0/vendor/bundle"
    state=directory
    owner=redmine
    group=redmine
    mode="u=rwx,g=rx,o=rx"
    recurse=yes

- name: "Install Redmine"
  bundler:
    state=present
    chdir="{{ redmine.app_base_path}}/{{ redmine.name }}/redmine-3.2.0/"
    gemfile="{{ redmine.app_base_path}}/{{ redmine.name }}/redmine-3.2.0/Gemfile"
    gem_path="{{ redmine.app_base_path}}/{{ redmine.name }}/redmine-3.2.0/vendor/bundle"
    exclude_groups="test development "
  become: yes
  become_user: "redmine"

- name: "Ensure Redmine Instance directory has correct user and file modes"
  file:
    path="{{ redmine.app_base_path}}/{{ redmine.name }}"
    state=directory
    owner=redmine
    group=redmine
    mode="u=rwx,g=rx,o=rx"
    recurse=yes

- name: "Generate Session Store Secret"
  command: bundle exec rake generate_secret_token
    creates="config/secrets.yml"
    chdir="{{ redmine.app_base_path}}/{{ redmine.name }}/redmine-3.2.0"
  environment:
    PATH: "{{ redmine.app_base_path}}/{{ redmine.name }}/redmine-3.2.0/vendor/bundle/ruby/2.0.0/bin:{{ lookup('env', 'PATH') }}"
  tags:
    - setup

- name: "Create Database Schema Objects"
  command: bundle exec rake db:migrate
    creates="db.exists"
    chdir="{{ redmine.app_base_path}}/{{ redmine.name }}/redmine-3.2.0"
  environment:
    PATH: "{{ redmine.app_base_path}}/{{ redmine.name }}/redmine-3.2.0/vendor/bundle/ruby/2.0.0/bin:{{ lookup('env', 'PATH') }}"
    RAILS_ENV: production
  tags:
    - setup

- name: "Load Database default data"
  command: bundle exec rake redmine:load_default_data
    creates="default_data.exists"
    chdir="{{ redmine.app_base_path}}/{{ redmine.name }}/redmine-3.2.0"
  environment:
    PATH: "{{ redmine.app_base_path}}/{{ redmine.name }}/redmine-3.2.0/vendor/bundle/ruby/2.0.0/bin:{{ lookup('env', 'PATH') }}"
    RAILS_ENV: production
    REDMINE_LANG: "{{ redmine.lang }}"
  tags:
    - setup

- name: "Ensure Redmine Instance directory has correct user and file modes"
  file:
    path="{{ redmine.app_base_path}}/{{ redmine.name }}"
    state=directory
    owner=redmine
    group=redmine
    mode="u=rx,g=rx,o=rx"
    recurse=yes

- name: "Ensure Redmine Instance sub directories has correct user and file modes"
  file:
    path="{{ redmine.app_base_path}}/{{ redmine.name }}/redmine-3.2.0/{{ item }}"
    state=directory
    owner=redmine
    group=redmine
    mode="u=rwx,g=rx,o=rx"
    recurse=yes
  with_items:
    - files
    - log
    - tmp
    - tmp/pdf
    - public/plugin_assets
  tags:
    - setup
