---
- name: "Setup Redmine Multi-Instance"
  debug:
    msg="Start Setup of Redmine Multi-Instance"

- include: base.yml

#-include: local_download

- name: "Start Setup Instance"
  debug:
    msg="Start setup of instance {{ item }}"
  with_dict: "{{ redmine_instance }}"

- include: instance.yml
  with_dict: "{{ redmine_instance }}"

- include: nginx.yml
  with_dict: "{{ redmine_instance }}"

- include: supervisor.yml
  with_dict: "{{ redmine_instance }}"

...
