---

- name: "Copy SSL Key components"
  copy:
    src="server-ssl/key/{{ redmine.domain }}_key.pem"
    dest="/etc/ssl/private/{{ redmine.domain }}_key.pem"
    force=yes
    owner=root
    group="ssl-cert"
    mode="u=rw,g=r,o="
  tags:
    - redmine_setup
    - redmine_upgrade

- name: "Copy SSL Cert"
  copy:
    src="server-ssl/crt/{{ redmine.domain }}_crt.pem"
    dest="/etc/ssl/certs/{{ redmine.domain }}_crt.pem"
    force=yes
    owner=root
    group="ssl-cert"
    mode="u=rw,g=r,o=r"
  tags:
    - redmine_setup
    - redmine_upgrade

- name: "Get LMU-CACERT-Chain"
  get_url:
    url="https://pki.pca.dfn.de/uni-muenchen-ca/pub/cacert/chain.txt"
    dest="/etc/ssl/certs/lmu-chain_crt.pem"
    owner=root
    group="ssl-cert"
    mode="u=rw,g=r,o=r"
    use_proxy=yes
    validate_certs=no
  environment:
    http_proxy: "{{ lookup('env', 'https_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
  tags:
    - redmine_setup
    - redmine_upgrade

- name: "Construct SSL-Certificate"
  shell: cat /etc/ssl/certs/{{ redmine.domain }}_crt.pem /etc/ssl/certs/lmu-chain_crt.pem > /etc/ssl/certs/{{ redmine.domain }}_chained_crt.pem
  tags:
    - redmine_setup
    - redmine_upgrade

- name: "Set permission for Chained-SSL-Certificate"
  file:
    path: /etc/ssl/certs/{{ redmine.domain }}_chained_crt.pem
    mode: 0755
    owner: root
    group: ssl-cert

- name: "Install vhost.confs for Redmine Multi-Instance sites"
  template:
    #src=nginx/nginx-redmine-multi-instance-wrapper.conf.j2
    src=nginx/nginx-redmine-multi-instance.conf.j2
    dest=/etc/nginx/sites-available/redmine-multi-instance.conf
    force=yes
    mode="u=rw,g=r,o=r"
    owner=root
    group=root
  notify:
    - "Reload NGINX"
  tags:
    - redmine_setup
    - redmine_upgrade

- name: "Activate vhost.confs (Create the link for site enabled specific configurations)"
  file:
    src=/etc/nginx/sites-available/redmine-multi-instance.conf
    path=/etc/nginx/sites-enabled/redmine-multi-instance.conf
    force=yes
    state=link
    owner=root
    group=root
  notify:
    - "Reload NGINX"
  tags:
    - redmine_setup
    - redmine_upgrade
