---

- name: "Copy SSL Key components"
  copy:
    src="server-ssl/key/{{ redmine.domain }}_key.pem"
    dest="/etc/ssl/private/{{ redmine.domain }}_key.pem"
    force=yes
    owner=root
    group=root
    mode="u=r,g=r,o="
  tags:
    - redmine_setup
    - redmine_upgrade

- name: "Get LMU-CACERT-Chain"
  get_url:
    url="https://pki.pca.dfn.de/uni-muenchen-ca/pub/cacert/chain.txt"
    dest="/etc/ssl/private/lmu-chain.pem"
    owner=root
    group=root
    mode="u=rw,g=r,o="
  tags:
    - redmine_setup
    - redmine_upgrade

- name: "Construct SSL-Certificate"
  assemble:
    src="files/server-ssl/crt/{{ redmine.domain}}.d/"
    dest="/etc/ssl/private/{{ redmine.domain }}_chained_crt.pem"
    remote_src=False
    mode="u=r,g=r,o="
    owner=root
    group=root
  tags:
    - redmine_setup
    - redmine_upgrade

- name: "Install vhost.confs for sites"
  template:
    src=templates/nginx-redmine-multi-instance-wrapper.conf.j2
    dest=/etc/nginx/sites-available/redmine-multiinstance.conf
    force=yes
    mode="u=rw,g=r,o=r"
    owner=root
    group=root
  notify:
    - "Reload NGINX"
  tags:
    - redmine_setup
    - redmine_upgrade

- name: "Activate vhost.confs (Create the link for site enabled specific configurations)"
  file:
    src=/etc/nginx/sites-available/redmine-multiinstance.conf
    path=/etc/nginx/sites-enabled/redmine-multiinstance.conf
    force=yes
    state=link
    owner=root
    group=root
  notify:
    - "Reload NGINX"
  tags:
    - redmine_setup
    - redmine_upgrade
