---

haproxy: {
  stats: {
    user: admin,
    password: admin,
    path: "/haproxy-status"
  },
  monitor: {
    enabled: true,
    path: "/haproxy-ping"
  },
  default_settings: {
    start: 1,
    something: 2
  }
}
