---

- name: "Setup Redmine Multi-Instance"
  debug:
    msg="Start Setup of Redmine Multi-Instance"

- include: base.yml
- include: ruby.yml

- name: "Setup Redmine Instances"
  debug:
    msg="Start Setup of Redmine Instances"

- include: instance.yml
  with_items: "{{ redmine_instance }}"
  loop_control:
    loop_var: instance


...
