---

- block:

  - name: "Ensure Ruby PPA is avaliable"
    apt_repository:
      repo="{{ redmine.ruby_ppa }}"
      state=present
    when: 'ansible_distribution == "Ubuntu" and redmine.use_ppa == "yes"'
    tags:
      - setup

  - name: "Ensure Ruby is installed"
    apt:
      pkg={{ item }}
      state=present
      update_cache=yes
      install_recommends=yes
    with_items:
      - "{{ redmine.ruby_version }}"
      - "{{ redmine.ruby_version }}-dev"
      - ruby-dev
      #- bundler
      - build-essential
      - git-core
      - git
      - subversion
      - gawk
      - libffi-dev
      - libgdbm-dev
      - libncurses5-dev
      - libreadline6-dev
      - libssl-dev
      - libyaml-dev
      - libxml2-dev
      - libxslt1-dev
    when: 'ansible_os_family == "Debian"'

  - name: "Ensure Ruby dependencies are installed"
    apt:
      pkg={{ item }}
      state=build-dep
      update_cache=no
      install_recommends=yes
    with_items:
      - imagemagick
      - libmagick++-dev
      - libmagickcore-dev
      - libmagickwand-dev
      - ruby-rmagick
    when: ansible_os_family == "Debian"


  - name: "Update bundler for Ruby"
    gem:
      name=bundler
      state=latest
      executable="{{ redmine.rubygem_version }}"
      user_install=no
    become: yes
    become_user: root

  environment:
    http_proxy: "{{ lookup('env', 'https_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"

...
