---

- block:

  - name: "Ensure Ruby dependencies are installed"
    yum:
      pkg={{ item }}
      state=present
      update_cache=no
    with_items:
      - patch
      - curl-devel
      - ImageMagick-devel
      - httpd-devel
      - libtool
      - apr-devel
      - apr-util-devel
      - ftp
      - gcc-c++
      - autoconf
      - readline
      - readline-devel
      - libyaml-devel
      - make
      - automake
      - bison
      - subversion
      - sqlite-devel

  - name: "Ensure Ruby is installed"
    yum:
      pkg={{ item }}
      state=present
      update_cache=no
    with_items:
      - rh-ruby23
      - rh-ruby23-ruby-devel
      - rh-ruby23-ruby-libs
      - rh-ruby23-rubygems
      - rh-ruby23-rubygems-devel
      - rh-ruby23-rubygem-bundler

#  - name: "Update bundler for Ruby"
#    gem:
#      name=bundler
#      state=latest
#      executable="{{ redmine.rubygem_version }}"
#      user_install=no
#    become: yes
#    become_user: root

  environment:
    http_proxy: "{{ lookup('env', 'https_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
  when: 'ansible_os_family == "RedHat"'

...
