---

# Special preseed rool for Vagrant

- name: "Ensure sudo-Groups exists"
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - sudo
    - wheel
    - ssh-login

- name: "Ensure Vagrant User is in Groups"
  user:
    name: vagrant
    comment: "Vagrant - Management User"
    state: present
    shell: "/bin/bash"
    groups:
      - vagrant
      - cdrom
      - floppy
      - audio
      - dip
      - video
      - plugdev
      - netdev
      - sudo
      - wheel
      - ssh-login
    system: no

