---

- name: "Ensure Ruby PPA is avaliable"
  apt_repository:
    repo="{{ foreman_ruby.ppa }}"
    state=present
  environment:
    http_proxy: "{{ lookup('env', 'https_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
  when: 'ansible_distribution == "Ubuntu" and foreman_ruby.use_ppa == "yes"'
  tags:
    - theforeman_setup
    - ruby_setup

- name: "Ensure Ruby is installed"
  apt:
    pkg={{ item }}
    state=present
    update_cache=no
    install_recommends=yes
  with_items:
    - "{{ foreman_ruby.version }}"
    - "{{ foreman_ruby.version }}-dev"
    - ruby-dev
    #- bundler
    - build-essential
    - git
    - gawk
    - libffi-dev
    - libgdbm-dev
    - libncurses5-dev
    - libreadline6-dev
    - libssl-dev
    - libyaml-dev
    - libxml2-dev
    - libxslt1-dev
  when: 'ansible_os_family == "Debian"'
  tags:
    - theforeman_setup
    - ruby_setup

...
