---

- name: "Ensure base dependencies for psdash are installed"
  apt:
    pkg={{ item }}
    state=present
    update_cache=yes
    install_recommends=yes
  with_items:
    - python-dev
    - python-virtualenv
    - build-essential
    - libzmq-dev
  when: ansible_os_family == "Debian"

- name: "Ensure psdash path: '{{ psdash.path }}' exists"
  file:
    path="{{ psdash.path }}"
    state=directory
    owner=root
    group=root
    mode="u=rwx,g=rwx,o=rx"

- name: "Install psdash"
  pip:
    name="psdash"
    state="latest"
    version="{{ psdash.version | default(omit)}}"
    virtualenv="{{ psdash.path }}"
    chdir="{{ psdash.path }}"
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"

- name: "Ensure psdash path: '{{ psdash.path }}' has right user settings and permissions"
  file:
    path="{{ psdash.path }}"
    state=directory
    owner=root
    group=root
    mode="u=rwx,g=rwx,o=rx"

- name: "Install Supervisor Conf for psdash-agent"
  template:
    src: psdash-agent-supervisor.conf.j2
    dest: "/etc/supervisor/conf.d/psdash.conf"
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  when: psdash.mode == "agent"
  #notify:
  #  - "Reload Supervisor"
  #  - "Restart Supervisor"

- name: "Install psdash-master.conf"
  template:
    src: psdash-master.py.j2
    dest: "/etc/psdash.py"
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  when: psdash.mode == "master"

- name: "Install Supervisor Conf for psdash-master"
  template:
    src: psdash-master-supervisor.conf.j2
    dest: "/etc/supervisor/conf.d/psdash-master.conf"
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  when: psdash.mode == "master"
  #notify:
  #  - "Reload Supervisor"
  #  - "Restart Supervisor"

- name: "Remove psdash"
  file:
    path="{{ psdash.path }}"
    state=absent
    owner=root
    group=root
    mode="u=rwx,g=rwx,o=rx"
  with_items:
    - "/etc/supervisor/conf.d/psdash.conf"
    - "/etc/psdash.py"
    - "{{ psdash.path }}"
  when: psdash.mode == "absent"
  notify:
    - "Reload Supervisor"
    - "Restart Supervisor"

- name: "Update Supervisorctl - Ensure psdash-agent are present"
  supervisorctl:
    name={{ item }}
    state=present
    username={{ supervisor.username }}
    password={{ supervisor.password }}
  with_items:
    - "psdash-agent"
  when: psdash.mode == "agent"

- name: "Start psdash-agent via Supervisor"
  supervisorctl:
    name={{ item }}
    state=started
    username={{ supervisor.username }}
    password={{ supervisor.password }}
  with_items:
    - "psdash-agent"
  when: psdash.mode == "agent"


- name: "Update Supervisorctl - Ensure psdash-master are present"
  supervisorctl:
    name={{ item }}
    state=present
    username={{ supervisor.username }}
    password={{ supervisor.password }}
  with_items:
    - "psdash-master"
  when: psdash.mode == "master"

- name: "Start psdash-master via Supervisor"
  supervisorctl:
    name={{ item }}
    state=started
    username={{ supervisor.username }}
    password={{ supervisor.password }}
  with_items:
    - "psdash-master"
  when: psdash.mode == "master"
