---

- name: Rename hostname to intended hostname
  hostname:
    name={{ inventory_hostname }}

- name: Ensure User "ansible" exists
  user:
    name=ansible
    comment="Ansible User for Provisioning with Ansible"
    state=present
    shell="/bin/bash"
    groups=sudo,
    system=yes

- name: Ensure that admin can login via SSH Public Key (Transfere Public Key)
  authorized_key: 
    user=ansible
    key="{{ lookup('file', '~/.ssh/id_rsa.pub')}}"
    state=present

- name: Update sshd_config
  template:
    dest="/etc/ssh/sshd_config"
    src="sshd_config.j2"
    owner=root
    group=root
    mode="u=rw,g=r,o=r"
  notify:
    - Reload sshd

- name: Ensure that User "ansible" can sudo with public key
  template:
    dest="/etc/sudoers"
    src="sudoers.j2"
    owner=root
    group=root
    mode="u=r,g=r,o="
    validate="visudo -cf %s"

- name: Ensure Base-Packages (common) are installed
  apt: 
    pkg={{ item }}
    state=present
    update_cache=yes
  with_items:
    - vim
    - aptitude
    - ssl-cert
    - update-notifier-common
    - software-properties-common
    - facter
    - ohai
    - python
    - python-dev
    - python-setuptools
    - python-pip
    - python-virtualenv
    - python3
    - python3-dev
    - python3-setuptools
    - python3-pip
    - curl
    - wget
    - bzip2
    - gzip
    - hv-kvp-daemon-init
#    - linux-tools
#    - linux-cloud-tools
  when: ansible_os_family == "Debian"
