---

- name: "Install ansible-cmdb"
  apt:
    deb: https://github.com/fboender/ansible-cmdb/releases/download/1.17/ansible-cmdb-1.17.deb
    state: latest

- name: "Ensure inventory file modes"
  file:
    path=/opt/lmu.ansible.playbooks/inventory/*
    state=file
    owner=fachadmin
    group=ansible
    mode=u=rw,g=rw,o=r

- name: "Ensure cmdb directories exists"
  file:
    path=/opt/lmu.ansible.playbooks/{{ item }}
    state=directory
    owner=fachadmin
    group=ansible
    mode=u=rwx,g=rwx,o=rx
  with_items:
    - out
    - cmdb

- name: "Install Cron-Tab for auto-generating Ansible-CMDB files frequently"
  cron:
    job="{{ item }}"
    state=present
    minute=*/5
    user=fachadmin
  with_items:
    - { name: "generate-facts",
        job: "ansible -u ansible -m setup --tree /opt/lmu.ansible.playbooks/out/ all"
      }
    - { name: "generate-cmdb-output",
        job: "ansible-cmdb -i /opt/lmu.ansible.playbooks/inventory /opt/lmu.ansible.playbooks/out/ > /opt/lmu.ansible.playbooks/cmdb/index.html"
      }

...
