---

- name: "Ensure Ansible Repository is present"
  apt_repository:
    repo="ppa:ansible/ansible"
    state=present
    #validate_certs=no
  environment:
    http_proxy: "{{ lookup('env', 'https_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
  when: ansible_distribution == "Ubuntu"
  tags:
    - ansible_setup

- name: "Install Ansible Packages"
  apt:
    pkg={{ item }}
    state=present
    update_cache=yes
    install_recommends=yes
  with_items:
    - software-properties-common
    - ansible
  when: ansible_os_family == "Debian"
  tags:
    - ansible_setup

- name: "Ensure Ansible directories are present"
  file:
    path={{ item }}
    state=directory
    owner=root
    group=root
    mode="u=rwx,g=rx,o=rx"
  with_items:
    - "/etc/ansible"
    - "/etc/ansible/roles"
    - "/usr/share/ansible/plugins"
    - "/usr/share/ansible/plugins/action"
    - "/usr/share/ansible/plugins/callback"
    - "/usr/share/ansible/plugins/connection"
    - "/usr/share/ansible/plugins/lookup"
    - "/usr/share/ansible/plugins/vars"
    - "/usr/share/ansible/plugins/filter"
    - "/usr/share/ansible/plugins/test"
    - "/usr/share/ansible/plugins/strategy"
    - "/usr/share/ansible/modules/"
    - "/usr/share/ansible/roles"
  tags:
    - ansible_setup

- name: "Copy Ansible Config files"
  template:
    src={{ item }}.j2
    dest="/etc/ansible/{{ item }}"
    force=yes
    owner=root
    group=root
    mode="u=rwx,g=rx,o=rx"
  with_items:
    - ansible.cfg
  tags:
    - ansible_setup
    - ansible_upgrade

...
