---

- name: "Ensure Ansible directories are present"
  file:
    path={{ item }}
    state=directory
    owner=root
    group=root
    mode="u=rwx,g=rx,o=rx"
  with_items:
    - "{{ ansible.path | default('/usr/local/venv-ansible') }}"
    - "/etc/ansible"
    - "/opt/ansible"
    - "/opt/ansible/roles"
    - "/usr/share/ansible/plugins"
    - "/usr/share/ansible/plugins/action"
    - "/usr/share/ansible/plugins/callback"
    - "/usr/share/ansible/plugins/connection"
    - "/usr/share/ansible/plugins/lookup"
    - "/usr/share/ansible/plugins/vars"
    - "/usr/share/ansible/plugins/filter"
    - "/usr/share/ansible/plugins/test"
    - "/usr/share/ansible/plugins/strategy"
    - "/usr/share/ansible/modules/"
    - "/usr/share/ansible/roles"
  tags:
    - setup

- name: "Set ansible requirements.txt"
  template:
    src: requirements.txt.j2
    dest: "{{ ansible.path | default('/usr/local/venv-ansible') }}/requirements.txt"
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  vars:
    req_items:
      - ansible
      - ansible-cmdb
      - ansible-inventory-grapher
      - ansible-roles-graph
  tags:
    - setup

- name: "Install Ansible"
  pip:
    requirements="{{ ansible.path | default('/usr/local/venv-ansible') }}/requirements.txt"
    state=latest
    virtualenv="{{ ansible.path | default('/usr/local/venv-ansible') }}"
    chdir="{{ ansible.path | default('/usr/local/venv-ansible') }}"
    virtualenv_python="python2.7"
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
  tags:
  - setup

- name: "Download lmu.ansible.playbooks"
  git:
    repo="https://github.com/lmu/lmu.ansible.playbooks.git"
    dest="/opt/lmu.ansible.playbooks"
    update=yes
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
  ignore_errors: yes
  tags:
    - setup
    - upgrade

- name: "Ensure playbook directories has correct owner and group"
  file:
    path="/opt/lmu.ansible.playbooks"
    state=directory
    owner="fachadmin"
    group="ansible"
    mode="u=rwx,g=rwx,o=rx"
    recurse=yes
  tags:
    - setup

- name: "Ensure Ansible directories links are present"
  file:
    path="{{ item.path }}"
    src="{{ item.src }}"
    state=link
    owner=root
    group=root
    mode="u=rwx,g=rx,o=rx"
  with_items:
    - { path: "/etc/ansible/inventory",  src: "/opt/lmu.ansible.playbooks/inventory" }
    - { path: "/etc/ansible/roles",      src: "/opt/ansible/roles" }
    - { path: "/etc/ansible/group_vars", src: "/opt/lmu.ansible.playbooks/group_vars" }
    - { path: "/etc/ansible/host_vars",  src: "/opt/lmu.ansible.playbooks/host_vars" }
  tags:
    - setup

- name: "Copy Ansible Config files"
  template:
    src="{{ item }}.j2"
    dest="/etc/ansible/{{ item }}"
    force=yes
    owner=root
    group=root
    mode="u=rwx,g=rx,o=rx"
  with_items:
    - ansible.cfg
  tags:
    - setup
    - upgrade

- name: "Include Ansible-CMDB"
  include: cmdb.yml

- name: "Include Web-Management-Interface"
  include: webinterface.yml

...
