---

- name: "Ensure Ansible Repository is present"
  apt_repository:
    repo="ppa:ansible/ansible"
    state=present
    #validate_certs=no
  environment:
    http_proxy: "{{ lookup('env', 'https_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
  when: ansible_distribution == "Ubuntu"
  tags:
    - ansible_setup

- name: "Install Ansible Packages"
  apt:
    pkg={{ item }}
    state=present
    update_cache=yes
    install_recommends=yes
  with_items:
    - software-properties-common
    - ansible
  when: ansible_os_family == "Debian"
  tags:
    - ansible_setup

- name: "Ensure Ansible directories are present"
  file:
    path={{ item }}
    state=directory
    owner=root
    group=root
    mode="u=rwx,g=rx,o=rx"
  with_items:
    - "/etc/ansible"
    - "/opt/ansible"
    - "/opt/ansible/roles"
    - "/usr/share/ansible/plugins"
    - "/usr/share/ansible/plugins/action"
    - "/usr/share/ansible/plugins/callback"
    - "/usr/share/ansible/plugins/connection"
    - "/usr/share/ansible/plugins/lookup"
    - "/usr/share/ansible/plugins/vars"
    - "/usr/share/ansible/plugins/filter"
    - "/usr/share/ansible/plugins/test"
    - "/usr/share/ansible/plugins/strategy"
    - "/usr/share/ansible/modules/"
    - "/usr/share/ansible/roles"
  tags:
    - ansible_setup

- name: "Download lmu.ansible.playbooks"
  git:
    repo="https://github.com/lmu/lmu.ansible.playbooks.git"
    dest="/opt/lmu.ansible.playbooks"
    update=yes
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"

- name: "Ensure playbook directories has correct owner and group"
  file:
    path="/opt/lmu.ansible.playbooks"
    state=directory
    owner=fachadmin
    group=ansible
    mode="u=rwx,g=rwx,o=rx"
    recurse=yes

- name: "Ensure Ansible directories links are present"
  file:
    path={{ item.path }}
    src={{ item.src }}
    state=link
    owner=root
    group=root
    mode="u=rwx,g=rx,o=rx"
  with_items:
    - { path: "/etc/ansible/inventory", src: "/opt/lmu.ansible.playbooks/inventory" }
    - { path: "/etc/ansible/roles", src: "/opt/ansible/roles" }
  tags:
    - ansible_setup

- name: "Copy Ansible Config files"
  template:
    src={{ item }}.j2
    dest="/etc/ansible/{{ item }}"
    force=yes
    owner=root
    group=root
    mode="u=rwx,g=rx,o=rx"
  with_items:
    - ansible.cfg
  tags:
    - ansible_setup
    - ansible_upgrade



...
