---

- name: "Ensure Python Passlib is present"
  apt:
    pkg={{ item }}
    state=present
    update_cache=yes
    install_recommends=yes
  with_items:
    - python-passlib
    - ldap-utils
  when: ansible_os_family == "Debian"
  tags:
    - setup
    - upgrade

- name: "Ensure VHost for Node-Master is absent"
  file:
    path="/etc/apache2/sites-enabled/master-node.conf"
    state=absent
  tags:
    - setup

- name: "Get LMU-CACERT-Chain"
  get_url:
    url="https://pki.pca.dfn.de/uni-muenchen-ca/pub/cacert/chain.txt"
    dest="/etc/ssl/private/lmu-chain.pem"
    owner="root"
    group="ssl-cert"
    mode="u=rw,g=r,o="
  environment:
    http_proxy: "{{ lookup('env', 'https_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
  tags:
    - setup
    - upgrade

- name: "Copy SSL Private-Key"
  copy:
    src="files/server-ssl/key/{{ ansible_fqdn }}_key.pem"
    dest="/etc/ssl/private/{{ ansible_fqdn }}_key.pem"
    force=yes
    owner=root
    group=root
    mode="u=r,g=r,o="
  tags:
    - setup
    - upgrade

- name: "Copy SSL Public Key"
  copy:
    src="files/server-ssl/crt/{{ ansible_fqdn }}_crt.pem"
    dest="/etc/ssl/certs/{{ ansible_fqdn }}_crt.pem"
    force=yes
    owner=root
    group=root
    mode="u=r,g=r,o="
  tags:
    - setup
    - upgrade

- name: "Ensure htpasswd user file is present"
  htpasswd:
    path="/etc/apache2/users"
    state=present
    name="{{ item.user }}"
    password="{{ item.password }}"
    owner="root"
    group="www-data"
    mode="u=rw,g=r,o="
    crypt_scheme=apr_md5_crypt
  with_items:
    - "{{ admin_users }}"
  tags:
    - setup
    - upgrade

- name: "Ensure htaccess group file is present"
  template:
    dest="/etc/apache2/groups"
    src="groups.j2"
    owner=root
    group=www-data
    mode="u=rw,g=r,o="
  tags:
    - setup
    - upgrade

#- name: "Generate Private-SSL-Key for Server"
#  openssl_privatekey:
#    path: "/etc/ssl/private/{{ ansible_fqdn }}.key"

#- name: "Generate Public-SSL-Key for Server"
#  openssl_privatekey:
#    path: "/etc/ssl/certs/{{ ansible_fqdn }}.pem"
#    privatekey_path: "/etc/ssl/private/{{ ansible_fqdn }}.key"

- name: "Ensure Apache Modules are activated"
  apache2_module:
    name="{{ item }}"
    state=present
  with_items:
    - proxy_http
    - proxy_ajp
    - auth_basic
    - authn_file
    - authz_user
    - authz_groupfile
    - authnz_ldap
    - authz_host
    - headers
  ignore_errors: yes
  notify:
    - "Restart Apache httpd"
  tags:
    - setup

- name: "Install VHost for Node-Master"
  template:
    dest="/etc/apache2/sites-available/master-node.conf"
    src="ansible-master-vhost.conf.j2"
    owner="root"
    group="root"
    mode="u=rw,g=r,o=r"
  notify:
    - "Restart Apache httpd"
  tags:
    - setup
    - upgrade

- name: "Ensure VHost for Node-Master is activated"
  file:
    src="/etc/apache2/sites-available/master-node.conf"
    dest="/etc/apache2/sites-enabled/master-node.conf"
    state=link
    force=yes
    mode="u=rw,g=r,o=r"
    owner="root"
    group="root"
  notify:
    - "Restart Apache httpd"
  tags:
    - setup

- name: "Generate index.html for Node-Master"
  template:
    dest="/var/www/html/index.html"
    src="ansible-master-index.html.j2"
    owner="root"
    group="root"
    mode="u=rw,g=r,o=r"
  tags:
    - setup
    - upgrade
    - web-overview-update

...
