
- block:
  # "Install Supervisor via Debian / Ubuntu Repository"

  - name: "Install supervisor"
    apt:
      pkg=supervisor
      state=present
    when: ansible_os_family == "Debian"

  when: '"{{ supervisor.use_system | default("no") }}" == "yes"'

- block:
  # "Install Supervisor via Python Package Index"

  - name: "Install Supervisor"
    pip:
      name="{{ item }}"
      state="present"
      version="{{ supervisor.version | default(omit)}}"
      virtualenv="{{ supervisor.path | default('/usr/local/venv-supervisor') }}"
      chdir="{{ supervisor.path | default('/usr/local/venv-supervisor') }}"
      #virtualenv_python=""
    with_items:
      - supervisor
      - superlance
    environment:
      http_proxy: "{{ lookup('env', 'http_proxy') }}"
      https_proxy: "{{ lookup('env', 'https_proxy') }}"

  - name: "Install Supervisor Init-Script"
    template:
      src="supervisord.init.j2"
      dest="/etc/init.d/supervisor"
      owner=root
      group=root
      mode="u=rw,g=r,o=r"
      validate=""
    when: ansible_os_family == "Debian"

  when: '"{{ supervisor.use_system | default("no") }}" == "no"'

- name: "Ensure supervisor Directory exists"
  file:
    path="{{ item }}"
    state=directory
    owner=root
    group=root
    mode="u=rwx,g=rx,o=rx"
  with_items:
    - "/etc/supervisor"
    - "/etc/supervisor/conf.d"
    - "/var/log/supervisor"

- name: "Copy supervisor global configuration"
  template:
    src="supervisord.conf.j2"
    dest="/etc/supervisor/supervisord.conf"
    owner=root
    group=root
    mode="u=rw,g=r,o=r"
    validate=""

- name: "Start the Supervisor service and enable on boot"
  service:
    name=supervisor
    state=started
    enabled=yes
