
- name: install supervisor debian/ubuntu
  apt: pkg=supervisor state=latest
  when: ansible_os_family == "Debian"

- name: ensure supervisor conf.d directory exists
  file:
    path: /etc/supervisor/conf.d
    state: directory

- name: ensure supervisor log directory exists
  file:
    path: /var/log/supervisor
    state: directory

- name: Copy supervisor global configuration
  template: 
    src=supervisord.conf
    dest=/etc/supervisord.conf
    owner=root
    group=root
    mode="u=rw,g=r,o=r"
    validate=""
