---

- name: "Install the Apache httpd packages"
  apt: name={{ item }} state=present update_cache=no
  with_items:
    - ssl-cert
    - apache2
    #- apache2-mpm-worker
    #- libapache2-mod-proxy-html
    #- libapache2-mod
    #- libapache2-mod-shib2
    #- libapache2-mod-xsendfile
    # Some additional tools for debuging and maintenance
    - libapache2-mod-log-slow
    - apache2-utils
    - apachetop
  when: ansible_os_family == "Debian"

- name: "Enable common used Apache httpd modules"
  apache2_module:
    name={{ item }}
    state=present
  with_items:
    - rewrite
    - ssl
    - proxy_http
    - headers

- name: "Ensure the directories (sites-available and sites-enabled) for site specific configurations are present"
  file: 
    path=/etc/apache2/{{ item }}
    state=directory
    owner=root
    group=root
    mode="u=rwx,g=rx,o=rx"
  with_items:
    - "sites-available"
    - "sites-enabled"
    - "includes"

- name: "Ensure the Apache httpd service is started and enable on boot"
  service:
    name=apache2
    state=started
    enabled=yes
  ignore_errors: True
