---

- debug:
    msg: "Redmine specific HTTPD setup"

- name: "include OS-specific variables"
  include_vars: "{{ ansible_os_family }}.yml"

- include: "{{ ansible_os_family }}.yml"

- name: "Ensure redmine vhosts.d folder exists"
  file:
    path="/etc/{{ apache2_conf_dir }}/includes/redmine.d"
    state=directory
    owner=root
    group=root
    mode="u=rwx,g=rx,o=rx"

- name: "Install redmine.conf"
  template:
    src="redmine.conf.j2"
    dest="/etc/{{ apache2_conf_dir }}/sites-available/redmine.conf"
    force=yes
    mode="u=rw,g=r,o=r"
    owner=root
    group=root
  notify:
    - "Reload Apache httpd"
  tags:
    - redmine_setup
    - redmine_upgrade

- name: "Generate include for Redmine instance"
  template:
    src="redmine_instance.conf.j2"
    dest="/etc/{{ apache2_conf_dir }}/includes/redmine.d/{{ instance.name }}.conf"
    force=yes
    mode="u=rw,g=r,o=r"
    owner=root
    group=root
  with_items: "{{ redmine_instance }}"
  loop_control:
    loop_var: instance
  notify:
    - "Reload Apache httpd"
  tags:
    - redmine_setup
    - redmine_upgrade

- name: "Activate redmine.conf"
  file:
    src="/etc/{{ apache2_conf_dir }}/sites-available/redmine.conf"
    dest="/etc/{{ apache2_conf_dir }}/sites-enabled/redmine.conf"
    state=link
    force=yes
    mode="u=rw,g=r,o=r"
    owner=root
    group=root
  notify:
    - "Reload Apache httpd"
  tags:
    - redmine_setup
    - redmine_upgrade
