---

- name: "Install Apache httpd Modules"
  yum:
    name={{ item }}
    state=present
    update_cache=no
  with_items:
    - mod_passenger
    - mod_info
    # Some additional tools for debuging and maintenance
  when: ansible_os_family == "RedHat"
  tags:
    - setup
    - upgrade

- name: "Enable Apache httpd passenger module"
  apache2_module:
    name=passenger
    state=present
  notify:
    - "Reload Apache httpd"

...
