---

- name: "Install Apache httpd Modules"
  yum:
    name={{ item }}
    state=present
    update_cache=no
  with_items:
    - mod_passenger
    # Some additional tools for debuging and maintenance
  when: ansible_os_family == "RedHat"
  tags:
    - setup
    - upgrade

- name: "Enable Apache httpd passenger module"
  apache2_module:
    name=passenger
    state=present
  notify:
    - "Reload Apache httpd"

- name: "Ensure redmine vhosts.d folder exists"
  file:
    path=/etc/apache2/includes/redmine.d
    state=directory
    owner=root
    group=root
    mode="u=rwx,g=rx,o=rx"

- name: "Install redmine.conf"
  template:
    src="redmine.conf.j2"
    dest="/etc/apache2/sites-available/redmine.conf"
    force=yes
    mode="u=rw,g=r,o=r"
    owner=root
    group=root
  notify:
    - "Reload Apache httpd"
  tags:
    - redmine_setup
    - redmine_upgrade

- name: "Generate include for Redmine instance"
  template:
    src="redmine_instance.conf.j2"
    dest="/etc/apache2/includes/redmine.d/{{ instance.name }}.conf"
    force=yes
    mode="u=rw,g=r,o=r"
    owner=root
    group=root
  with_items: "{{ redmine_instance }}"
  loop_control:
    loop_var: instance
  notify:
    - "Reload Apache httpd"
  tags:
    - redmine_setup
    - redmine_upgrade

- name: "Activate redmine.conf"
  file:
    src="/etc/apache2/sites-available/redmine.conf"
    dest="/etc/apache2/sites-enabled/redmine.conf"
    state=link
    force=yes
    mode="u=rw,g=r,o=r"
    owner=root
    group=root
  notify:
    - "Reload Apache httpd"
  tags:
    - redmine_setup
    - redmine_upgrade
