---

- name: "Reload sshd"
  service:
    name: "{{ item }}"
    state: reloaded
  with_items:
    - ssh
  ignore_errors: yes
  when: ansible_os_family == "Debian"

- name: "Reload sshd"
  service:
    name: "{{ item }}"
    state: reloaded
  with_items:
    - sshd
  ignore_errors: yes
  when: ansible_os_family == "RedHat"

...
