---

- name: "Ensure Global Repository settings are set correct"
  copy:
    dest="/etc/yum.repos.d/{{ item }}"
    src="yum-repos/{{ item }}"
    mode="u=rw,g=r,o=r"
    owner=root
    group=root
  with_items:
  - "CentOS-Base.repo"
  - "CentOS-CR.repo"
  - "CentOS-Debuginfo.repo"
  - "CentOS-fasttrack.repo"
  - "CentOS-Media.repo"
  - "CentOS-SCLo-scl-rh.repo"
  - "CentOS-SCLo-scl.repo"
  - "CentOS-Sources.repo"
  - "CentOS-Vault.repo"
  - "epel-testing.repo"
  - "epel.repo"
  - "ZUV-RPM.repo"

- name: "Ensure Base-Packages (ZUV-common) are installed"
  yum:
    pkg="{{ item }}"
    state=present
    update_cache=yes
  with_items:
    - zuv-bginfo-centos
    - zuv-certs-centos
  when: ansible_os_family == "RedHat" and ansible_distribution == "CentOS"
  notify:
    - Restart xinetd

...
