---

# Additional Specific Settings for Ubuntu 14.04 LTS
#

- block:

  - name: "Ensure current Kernel-Packages (Hyper-V Support) are installed"
    apt:
      pkg={{ item }}
      state=present
      update_cache=no
    with_items:
      # Kernelmodules for hyper-v support
      - linux-firmware
      # Kernel Pflege
      - bikeshed

  - name: "Purge old Kernels"
    command: purge-old-kernels -y

  - name: "Autoremove old unnecessary packages"
    command: apt-get autoremove -y

  - name: "Autoclean old unnecessary packages"
    command: apt-get autoclean -y

  - name: "Clean Apt Cache"
    command: apt-get clean -y

  when: 'ansible_os_family == "Debian" and ansible_distribution == "Ubuntu" and ansible_distribution_release == "bionic"'


...
