---

- name: Change Password for "fachadmin"
  user:
    name=fachadmin
    password={{ fachadmin_password }}
    update_password=always

- name: Make ZUV-Proxy Settings
  template:
    dest=/etc/apt/source.list
    src=zuv_source.list
    mode="o=rw,g=r,u=r"
    owner=root
    group=root

- name: Make APT respect ZUV-Proxy Settings

- name: Install ZUV-Proxy-CA

- name: Add alias for "pip" to always use ZUV-Proxy-CA

- name: Update apt/source.list

- name: Update sshd_config

- name: Install base-Packages (common)
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - vim
    - aptitude
    - update-notifier-common
  when: ansible_os_family == "Debian"
