---

- name: "Ensure Base-Packages (ZUV-common) are installed"
  zypper:
    pkg="{{ item }}"
    state=present
    update_cache=no
  with_items:
    - zuv-bginfo-sles
    - zuv-bginfo-sles
    - zuv-certs-sles
  when: ansible_os_family == "Suse" and ansible_distribution == "SLES"
  notify:
    - Restart xinetd

...
