---

- name: "Update apt/sources.list"
  template:
    dest="/etc/apt/sources.list"
    src="zuv_source.list.j2"
    mode="u=rw,g=r,o=r"
    owner=root
    group=root

- name: "Update Apt-Keys"
  apt_key:
    url="http://apt.verwaltung.uni-muenchen.de/ZUV-DEB/conf/Ref.VI.2.public.gpg"
    state=present
  ignore_errors: yes
  when: ansible_os_family == "Debian"

- name: "Install Check_MK Agenet"
  apt:
    deb=http://monitor.zuv.uni-muenchen.de/nagios/check_mk/agents/check-mk-agent-1.4.0.p31-1_all.deb

- name: "Ensure Base-Packages (ZUV-common) are installed"
  apt:
    pkg="{{ item }}"
    state=present
    update_cache=yes
  with_items:
    - bginfo-ubuntu
    - certs-zuv-ubuntu
  when: ansible_os_family == "Debian" and ansible_distribution == "Ubuntu"
  notify:
    - Restart xinetd

...
