---

dependencies:

  - { role: base-preseed,
    }
  - { role: lmu.ansible_role.firewalld,
    }
  - { role: lmu.ansible_role.mariadb,
    }
  - { role: memcached,
    }
  - { role: apache_httpd,
    }
  - { role: lmu.ansible_role.php7,
    }

...
