---

- name: "Install PostgreSQL Packages"
  apt:
    pkg={{ item }}
    state=present
    install_recommends=yes
  with_items:
    - postgresql
    - postgresql-contrib
    - postgresql-client
    - python-psycopg2
    - libpq-dev
    - pgtop
#    - postgres-xc
  when: ansible_os_family == "Debian"

- name: "Install PostgreSQL Python bindings"
  pip:
    name=psycopg2

- name: "Copy the configuration files for PostgreSQL"
  template:
    src={{ item }}.j2
    dest=/etc/postgresql/9.3/main/{{ item }}
    force=yes
    owner=postgres
    group=postgres
    mode="u=rw,g=r,o=r"
  with_items:
    - postgresql.conf
    - pg_ident.conf
    - pg_hba.conf
    - start.conf
  notify:
    - "Restart PostgreSQL"

- name: "Ensure PostgreSQL Data Directory exists"
  file:
    path="{{ database.data_directory }}"
    state=directory
    owner=postgres
    group=postgres
    mode="u=rwx,g=,o="

- name: "Check Data Directory"
  stat:
    path="{{ database.data_directory }}"
  register: pg_data_dir

- name: "Generate Locale"
  command: locale-gen 'de_DE.UTF-8'
  become: true

- name: "Initialize PostgreSQL"
  command: initdb -D {{ database.data_directory }}
  become_user: postgres
  when: "pg_data_dir.stat.path != '/var/lib/postgresql/9.3/main'"

- name: "Ensure PostgreSQL is started and enabled on boot."
  service:
    name=postgresql
    state=restarted
    enabled=yes
