- name: install postgresql packages
  apt: pkg={{ item }} state=latest
  with_items:
    - postgresql
    - postgresql-contrib
    - postgresql-client
    - libpq-dev
    - pgtop
  when: ansible_os_family == "Debian"

- name: install postgresql python bindings
  pip: name=psycopg2
