---

- name: "Ensure psycopg2 path: '{{ psycopg2.path | default('/usr/local/venv-psycopg2') }}' exists"
  file:
    path="{{ psycopg2.path | default('/usr/local/venv-psycopg2') }}"
    state=directory
    owner=root
    group=root
    mode="u=rwx,g=rwx,o=rx"

- name: "Set psycopg2 requirements.txt"
  template:
    src: requirements.txt.j2
    dest: "{{ psycopg2.path | default('/usr/local/venv-psycopg2') }}/requirements.txt"
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  vars:
    req_items:
      - "psycopg2<2.7"

- name: "Install psycopg2 - postgres bindings for ansible"
  pip:
    requirements="{{ psycopg2.path | default('/usr/local/venv-psycopg2') }}/requirements.txt"
    state=present
    virtualenv="{{ psycopg2.path | default('/usr/local/venv-psycopg2') }}"
    chdir="{{ psycopg2.path | default('/usr/local/venv-psycopg2') }}"
  become: yes
  become_user: root
  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    #PATH: "/opt/rh/rh-postgresql95/root/usr/bin:{{ lookup('env', 'PATH')}}"
    #LD_LIBRARY_PATH: "/opt/rh/rh-postgresql95/root/usr/lib64"
    #LIBRARY_PATH: "/opt/rh/rh-postgresql95/root/usr/lib64"

...
