---

dependencies:

  - { role: postgres,
    }

  - { role: nginx,
    }

  - { role: postfix,
      
    }

#  - { role: apache_httpd,
#    }

  - { role: supervisor,
    }

  - { role: memcached,
    }

...
